server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    driver-class-name: org.postgresql.Driver
    username: portfolio
    password: 1111
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
          timeout: 10000
      jakarta:
        persistence:
          lock:
            timeout: 10000
