spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${PORTFOLIO_GITHUB_CLIENT_ID:sample-key}
            client-secret: ${PORTFOLIO_GITHUB_CLIENT_SECRET:secret-key}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${PORTFOLIO_JWT_SECRET:12345678901234567890123456789012}
  expiration: 86400000 # 24시간

aws:
  s3:
    bucket-name: ${PORTFOLIO_AWS_S3_BUCKET_NAME:portfolio-files}
    region: ${PORTFOLIO_AWS_REGION:ap-northeast-2}
    access-key: ${PORTFOLIO_AWS_ACCESS_KEY}
    secret-key: ${PORTFOLIO_AWS_SECRET_KEY}

cors:
  allowed-origins:
    - http://localhost:8080
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
